In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv') 
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action','Adventure','Fantasy','SciFi']

In [17]:
def convert(obj):
    L=[]
    for i in ast.literal_eval (obj):
        L.append(i['name'])
    return L

In [16]:

import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
# movies['genres'] = movies['genres'].apply(convert)
# movies['keywords'] = movies['keywords'].apply(convert)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['keywords'] = movies['keywords'].apply(convert)

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
def convert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [22]:
movies['cast'] = movies['cast'].apply(convert3)

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval (obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [26]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [28]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [29]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [33]:
movies['tags'] = movies['overview'] + movies['genres']+ movies['keywords']+ movies['cast'] + movies['crew']

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [35]:
new_df = movies[['movie_id','title','tags']]

In [36]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\amank\AppData\Local\Temp\ipykernel_23044\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [37]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [38]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " A c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " A d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " F a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " S c i e n c e  F i c t i o n " } ] cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [39]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\amank\AppData\Local\Temp\ipykernel_23044\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [67]:
import nltk

In [68]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [73]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [76]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\amank\AppData\Local\Temp\ipykernel_23044\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [41]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [42]:
new_df['tags'][1]

'captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. [ { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ] ocean drugabuse exoticisland eastindiatradingcompany loveofone\'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski'

In [43]:
# import sklearn

In [77]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [78]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [79]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [80]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [81]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [82]:
['loved','loving','love']
['love','love','love']

['love', 'love', 'love']

In [83]:
ps.stem('dancing')

'danc'

In [74]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. [ { " i d " : 2 8 , " n a m e " : " a c t i o n " } , { " i d " : 1 2 , " n a m e " : " a d v e n t u r e " } , { " i d " : 1 4 , " n a m e " : " f a n t a s y " } , { " i d " : 8 7 8 , " n a m e " : " s c i e n c e f i c t i o n " } ] cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [84]:
from sklearn.metrics.pairwise import cosine_similarity

In [86]:
similarity = cosine_similarity(vectors)

In [98]:
similarity[1]

array([0.        , 1.        , 0.        , ..., 0.02592379, 0.        ,
       0.0277137 ])

In [99]:
list(enumerate(similarity[1]))

[(0, 0.0),
 (1, 1.0000000000000002),
 (2, 0.0),
 (3, 0.021166687833365085),
 (4, 0.02707651805369412),
 (5, 0.049341371149144844),
 (6, 0.0),
 (7, 0.05751973085430508),
 (8, 0.0),
 (9, 0.0),
 (10, 0.029934217004462485),
 (11, 0.0),
 (12, 0.3522349768381735),
 (13, 0.051315800579078544),
 (14, 0.05986843400892497),
 (15, 0.048435947969648285),
 (16, 0.030358837035945812),
 (17, 0.18396881992730957),
 (18, 0.042933879074109185),
 (19, 0.04716666306365782),
 (20, 0.016260700012185932),
 (21, 0.0),
 (22, 0.03829197905337418),
 (23, 0.0),
 (24, 0.09240616554505461),
 (25, 0.11487593716012252),
 (26, 0.059053859535749265),
 (27, 0.04757860680698065),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0508000508000762),
 (31, 0.037450294313656915),
 (32, 0.024670685574572422),
 (33, 0.03919309008348103),
 (34, 0.037450294313656915),
 (35, 0.03919309008348103),
 (36, 0.028049635672660722),
 (37, 0.0),
 (38, 0.0689883074727411),
 (39, 0.0),
 (40, 0.031750031750047626),
 (41, 0.05477910356647767),
 (42, 0.0),
 (43, 0.05184758473652127),
 (44, 0.0),
 (45, 0.04716666306365782),
 (46, 0.032791291789197645),
 (47, 0.0891091838708226),
 (48, 0.07200230411059791),
 (49, 0.033351867298253506),
 (50, 0.0),
 (51, 0.0),
 (52, 0.028049635672660722),
 (53, 0.07265392195447243),
 (54, 0.0),
 (55, 0.020207175225248872),
 (56, 0.0),
 (57, 0.16433731069943303),
 (58, 0.05296271413323761),
 (59, 0.06140377126253594),
 (60, 0.0),
 (61, 0.04016096644512494),
 (62, 0.049813548138671795),
 (63, 0.023186944788008413),
 (64, 0.033351867298253506),
 (65, 0.0),
 (66, 0.10592542826647522),
 (67, 0.0),
 (68, 0.03522349768381735),
 (69, 0.059254382556024304),
 (70, 0.0),
 (71, 0.028049635672660722),
 (72, 0.032791291789197645),
 (73, 0.0),
 (74, 0.0508000508000762),
 (75, 0.11810771907149853),
 (76, 0.0),
 (77, 0.04939317312787276),
 (78, 0.0),
 (79, 0.07074999459548673),
 (80, 0.0),
 (81, 0.0420424211834425),
 (82, 0.0),
 (83, 0.0),
 (84, 0.0),
 (85, 0.09165444688834581),
 (86, 0.0),
 (87, 0.0),
 (88, 0.03666177875533833),
 (89, 0.032388929412563196),
 (90, 0.03666177875533833),
 (91, 0.09677419354838712),
 (92, 0.023789303403490326),
 (93, 0.02707651805369412),
 (94, 0.07658395810674835),
 (95, 0.0),
 (96, 0.030358837035945812),
 (97, 0.05415303610738824),
 (98, 0.05751973085430508),
 (99, 0.03080205518168487),
 (100, 0.0),
 (101, 0.029526929767874632),
 (102, 0.02358333153182891),
 (103, 0.022996102490913696),
 (104, 0.09837387536759294),
 (105, 0.03919309008348103),
 (106, 0.09600307214746387),
 (107, 0.0),
 (108, 0.0),
 (109, 0.11487593716012254),
 (110, 0.026198125853112306),
 (111, 0.02875986542715254),
 (112, 0.0),
 (113, 0.0),
 (114, 0.0),
 (115, 0.049341371149144844),
 (116, 0.028049635672660722),
 (117, 0.03522349768381735),
 (118, 0.0),
 (119, 0.025149772741392844),
 (120, 0.0),
 (121, 0.0),
 (122, 0.06913011298202835),
 (123, 0.0),
 (124, 0.0535479552601666),
 (125, 0.07121813478786003),
 (126, 0.03080205518168487),
 (127, 0.042630455631948755),
 (128, 0.031750031750047626),
 (129, 0.07944407119985641),
 (130, 0.032791291789197645),
 (131, 0.0),
 (132, 0.05029954548278569),
 (133, 0.03225806451612904),
 (134, 0.0),
 (135, 0.0),
 (136, 0.08122955416108235),
 (137, 0.016821577756312225),
 (138, 0.06160411036336974),
 (139, 0.023186944788008413),
 (140, 0.025657900289539272),
 (141, 0.0),
 (142, 0.03456505649101418),
 (143, 0.05029954548278569),
 (144, 0.0),
 (145, 0.04356068418690321),
 (146, 0.018624202231923414),
 (147, 0.0),
 (148, 0.0),
 (149, 0.022107884414269093),
 (150, 0.06221710168382551),
 (151, 0.0),
 (152, 0.0),
 (153, 0.02227729596770565),
 (154, 0.0),
 (155, 0.0),
 (156, 0.022809896167307987),
 (157, 0.0),
 (158, 0.05184758473652127),
 (159, 0.0),
 (160, 0.0),
 (161, 0.0),
 (162, 0.037450294313656915),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.0),
 (167, 0.07658395810674835),
 (168, 0.029934217004462485),
 (169, 0.07544931822417852),
 (170, 0.024217973984824143),
 (171, 0.1016001016001524),
 (172, 0.0),
 (173, 0.0535479552601666),
 (174, 0.029934217004462485),
 (175, 0.0),
 (176, 0.03456505649101418),
 (177, 0.0),
 (178, 0.0885807893036239),
 (179, 0.0),
 (180, 0.0),
 (181, 0.025923792368260635),
 (182, 0.0267739776300833),
 (183, 0.03966817518790096),
 (184, 0.029526929767874632),
 (185, 0.0),
 (186, 0.0),
 (187, 0.06451612903225808),
 (188, 0.0),
 (189, 0.04490132550669373),
 (190, 0.09776474334756886),
 (191, 0.08414890701798217),
 (192, 0.05296271413323761),
 (193, 0.1061822175603132),
 (194, 0.0),
 (195, 0.0),
 (196, 0.03080205518168487),
 (197, 0.041757384532966166),
 (198, 0.0),
 (199, 0.2220361701711518),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.0),
 (206, 0.041757384532966166),
 (207, 0.029526929767874632),
 (208, 0.0),
 (209, 0.041204282171516456),
 (210, 0.0),
 (211, 0.0),
 (212, 0.0),
 (213, 0.0),
 (214, 0.0),
 (215, 0.0254000254000381),
 (216, 0.1531679162134967),
 (217, 0.024441185836892216),
 (218, 0.0),
 (219, 0.0),
 (220, 0.06913011298202835),
 (221, 0.0),
 (222, 0.09123958466923195),
 (223, 0.029934217004462485),
 (224, 0.0),
 (225, 0.027389551783238836),
 (226, 0.0704469953676347),
 (227, 0.06253053994807226),
 (228, 0.0254000254000381),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (232, 0.032791291789197645),
 (233, 0.0),
 (234, 0.05415303610738824),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.021166687833365085),
 (239, 0.041204282171516456),
 (240, 0.0535479552601666),
 (241, 0.0),
 (242, 0.03126526997403613),
 (243, 0.02707651805369412),
 (244, 0.0),
 (245, 0.0),
 (246, 0.06582683985617241),
 (247, 0.03456505649101418),
 (248, 0.0),
 (249, 0.041204282171516456),
 (250, 0.03592106040535498),
 (251, 0.0),
 (252, 0.04676523735449557),
 (253, 0.0),
 (254, 0.0),
 (255, 0.029934217004462485),
 (256, 0.0),
 (257, 0.03080205518168487),
 (258, 0.0406725917391042),
 (259, 0.0),
 (260, 0.03592106040535498),
 (261, 0.0),
 (262, 0.024217973984824143),
 (263, 0.0),
 (264, 0.0),
 (265, 0.031750031750047626),
 (266, 0.028049635672660722),
 (267, 0.04233337566673017),
 (268, 0.0),
 (269, 0.03666177875533833),
 (270, 0.07544931822417852),
 (271, 0.05477910356647767),
 (272, 0.0),
 (273, 0.07200230411059791),
 (274, 0.014334063592841508),
 (275, 0.0),
 (276, 0.07332355751067667),
 (277, 0.0),
 (278, 0.0),
 (279, 0.026481357066618805),
 (280, 0.05986843400892497),
 (281, 0.049813548138671795),
 (282, 0.025149772741392844),
 (283, 0.032791291789197645),
 (284, 0.041204282171516456),
 (285, 0.04490132550669373),
 (286, 0.06683188790311695),
 (287, 0.029526929767874632),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (295, 0.03225806451612904),
 (296, 0.022809896167307987),
 (297, 0.0),
 (298, 0.0),
 (299, 0.022450662753346864),
 (300, 0.0),
 (301, 0.0),
 (302, 0.0),
 (303, 0.0),
 (304, 0.07332355751067665),
 (305, 0.024906774069335898),
 (306, 0.0),
 (307, 0.05233442719890389),
 (308, 0.0),
 (309, 0.0),
 (310, 0.10417859945721022),
 (311, 0.0),
 (312, 0.029526929767874632),
 (313, 0.0),
 (314, 0.0),
 (315, 0.03225806451612904),
 (316, 0.022450662753346864),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.03456505649101418),
 (324, 0.0),
 (325, 0.08466675133346034),
 (326, 0.0),
 (327, 0.03080205518168487),
 (328, 0.03126526997403613),
 (329, 0.030358837035945812),
 (330, 0.02875986542715254),
 (331, 0.0508000508000762),
 (332, 0.0),
 (333, 0.028398091712353243),
 (334, 0.056099271345321444),
 (335, 0.0267739776300833),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.028398091712353243),
 (340, 0.11219854269064289),
 (341, 0.0),
 (342, 0.0813451834782084),
 (343, 0.04356068418690321),
 (344, 0.0),
 (345, 0.026481357066618805),
 (346, 0.03225806451612904),
 (347, 0.0),
 (348, 0.03666177875533833),
 (349, 0.030358837035945812),
 (350, 0.0),
 (351, 0.025923792368260635),
 (352, 0.031750031750047626),
 (353, 0.0),
 (354, 0.0),
 (355, 0.020739033894608502),
 (356, 0.0),
 (357, 0.0),
 (358, 0.037450294313656915),
 (359, 0.11235088294097074),
 (360, 0.0),
 (361, 0.08519427513705972),
 (362, 0.0),
 (363, 0.02262814111007102),
 (364, 0.028049635672660722),
 (365, 0.0),
 (366, 0.0),
 (367, 0.0),
 (368, 0.0),
 (369, 0.0),
 (370, 0.0),
 (371, 0.0),
 (372, 0.02707651805369412),
 (373, 0.0),
 (374, 0.04525628222014204),
 (375, 0.022996102490913696),
 (376, 0.02707651805369412),
 (377, 0.026481357066618805),
 (378, 0.03592106040535498),
 (379, 0.03807624787725668),
 (380, 0.029934217004462485),
 (381, 0.0),
 (382, 0.0),
 (383, 0.024670685574572422),
 (384, 0.09837387536759293),
 (385, 0.032791291789197645),
 (386, 0.049813548138671795),
 (387, 0.0),
 (388, 0.025923792368260635),
 (389, 0.06788442333021306),
 (390, 0.0),
 (391, 0.06534102628035482),
 (392, 0.06913011298202835),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.060717674071891624),
 (398, 0.049813548138671795),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (402, 0.0),
 (403, 0.024441185836892216),
 (404, 0.0),
 (405, 0.032791291789197645),
 (406, 0.0),
 (407, 0.048435947969648285),
 (408, 0.0),
 (409, 0.05415303610738824),
 (410, 0.0),
 (411, 0.030358837035945812),
 (412, 0.11085479909473867),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (416, 0.029526929767874632),
 (417, 0.0),
 (418, 0.041204282171516456),
 (419, 0.026198125853112306),
 (420, 0.026198125853112306),
 (421, 0.0),
 (422, 0.0),
 (423, 0.023186944788008413),
 (424, 0.0),
 (425, 0.048435947969648285),
 (426, 0.020207175225248872),
 (427, 0.059053859535749265),
 (428, 0.020878692266483083),
 (429, 0.0),
 (430, 0.0),
 (431, 0.028398091712353243),
 (432, 0.025923792368260635),
 (433, 0.0),
 (434, 0.0267739776300833),
 (435, 0.04490132550669373),
 (436, 0.029526929767874632),
 (437, 0.029526929767874632),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.024906774069335898),
 (444, 0.027389551783238836),
 (445, 0.02875986542715254),
 (446, 0.0),
 (447, 0.0),
 (448, 0.04757860680698065),
 (449, 0.0),
 (450, 0.024217973984824143),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.05296271413323761),
 (455, 0.023186944788008413),
 (456, 0.0),
 (457, 0.06788442333021306),
 (458, 0.0254000254000381),
 (459, 0.0),
 (460, 0.056796183424706485),
 (461, 0.06558258357839529),
 (462, 0.036285750571483),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0),
 (467, 0.0),
 (468, 0.03225806451612904),
 (469, 0.0445545919354113),
 (470, 0.025923792368260635),
 (471, 0.048435947969648285),
 (472, 0.031750031750047626),
 (473, 0.02707651805369412),
 (474, 0.0),
 (475, 0.024906774069335898),
 (476, 0.0),
 (477, 0.0),
 (478, 0.0203362958695521),
 (479, 0.01983408759395048),
 (480, 0.056099271345321444),
 (481, 0.02707651805369412),
 (482, 0.0),
 (483, 0.03666177875533833),
 (484, 0.033351867298253506),
 (485, 0.03126526997403613),
 (486, 0.05388159060803248),
 (487, 0.037450294313656915),
 (488, 0.019255709562623336),
 (489, 0.048001536073731935),
 (490, 0.0),
 (491, 0.022809896167307987),
 (492, 0.059053859535749265),
 (493, 0.03424938726253709),
 (494, 0.04016096644512494),
 (495, 0.0),
 (496, 0.01914598952668709),
 (497, 0.03829197905337418),
 (498, 0.0),
 (499, 0.029526929767874632),
 (500, 0.0),
 (501, 0.0),
 (502, 0.05029954548278569),
 (503, 0.0),
 (504, 0.03666177875533833),
 (505, 0.0),
 (506, 0.0),
 (507, 0.024217973984824143),
 (508, 0.05986843400892497),
 (509, 0.05296271413323761),
 (510, 0.0),
 (511, 0.03592106040535498),
 (512, 0.0),
 (513, 0.0),
 (514, 0.030358837035945812),
 (515, 0.056099271345321444),
 (516, 0.0),
 (517, 0.06788442333021305),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.033351867298253506),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (529, 0.0),
 (530, 0.06558258357839529),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (535, 0.0),
 (536, 0.0267739776300833),
 (537, 0.0),
 (538, 0.0),
 (539, 0.0),
 (540, 0.0),
 (541, 0.024000768036865967),
 (542, 0.04233337566673017),
 (543, 0.05542739954736933),
 (544, 0.032791291789197645),
 (545, 0.028398091712353243),
 (546, 0.03829197905337418),
 (547, 0.0),
 (548, 0.0),
 (549, 0.08032193289024989),
 (550, 0.0),
 (551, 0.06394568344792313),
 (552, 0.0),
 (553, 0.0),
 (554, 0.031750031750047626),
 (555, 0.0),
 (556, 0.0),
 (557, 0.0),
 (558, 0.0),
 (559, 0.03456505649101418),
 (560, 0.04016096644512494),
 (561, 0.0),
 (562, 0.0),
 (563, 0.030358837035945812),
 (564, 0.03666177875533833),
 (565, 0.025149772741392844),
 (566, 0.05542739954736933),
 (567, 0.0),
 (568, 0.0),
 (569, 0.08414890701798217),
 (570, 0.0),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0535479552601666),
 (576, 0.030358837035945812),
 (577, 0.0),
 (578, 0.022450662753346864),
 (579, 0.0),
 (580, 0.0),
 (581, 0.06913011298202835),
 (582, 0.025149772741392844),
 (583, 0.08526091126389751),
 (584, 0.046373889576016826),
 (585, 0.028398091712353243),
 (586, 0.0),
 (587, 0.08216865534971651),
 (588, 0.02913582733740325),
 (589, 0.0),
 (590, 0.0),
 (591, 0.0),
 (592, 0.048001536073731935),
 (593, 0.021315227815974377),
 (594, 0.0),
 (595, 0.0),
 (596, 0.027389551783238836),
 (597, 0.03456505649101418),
 (598, 0.0),
 (599, 0.015515534948793472),
 (600, 0.0),
 (601, 0.03807624787725668),
 (602, 0.025923792368260635),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.06735198826004059),
 (608, 0.0),
 (609, 0.0267739776300833),
 (610, 0.03265550945941362),
 (611, 0.0),
 (612, 0.048435947969648285),
 (613, 0.0),
 (614, 0.05542739954736933),
 (615, 0.0),
 (616, 0.03919309008348103),
 (617, 0.0),
 (618, 0.026198125853112306),
 (619, 0.05751973085430508),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.05029954548278569),
 (624, 0.0),
 (625, 0.0),
 (626, 0.031750031750047626),
 (627, 0.0),
 (628, 0.056099271345321444),
 (629, 0.028049635672660722),
 (630, 0.027713699773684666),
 (631, 0.0),
 (632, 0.0),
 (633, 0.025657900289539272),
 (634, 0.028049635672660722),
 (635, 0.024670685574572422),
 (636, 0.0535479552601666),
 (637, 0.0),
 (638, 0.0),
 (639, 0.02707651805369412),
 (640, 0.022450662753346864),
 (641, 0.0),
 (642, 0.03592106040535498),
 (643, 0.02875986542715254),
 (644, 0.0),
 (645, 0.0254000254000381),
 (646, 0.060717674071891624),
 (647, 0.0),
 (648, 0.0),
 (649, 0.11973686801784994),
 (650, 0.029526929767874632),
 (651, 0.08740748201220976),
 (652, 0.0),
 (653, 0.0),
 (654, 0.024217973984824143),
 (655, 0.0),
 (656, 0.027713699773684666),
 (657, 0.058442790592989444),
 (658, 0.05542739954736933),
 (659, 0.0885807893036239),
 (660, 0.03829197905337418),
 (661, 0.024217973984824143),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0704469953676347),
 (665, 0.0267739776300833),
 (666, 0.028398091712353243),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0),
 (674, 0.027389551783238836),
 (675, 0.0254000254000381),
 (676, 0.03456505649101418),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.0),
 (685, 0.0),
 (686, 0.07490058862731383),
 (687, 0.0),
 (688, 0.024441185836892216),
 (689, 0.059053859535749265),
 (690, 0.02875986542715254),
 (691, 0.03456505649101418),
 (692, 0.0254000254000381),
 (693, 0.0),
 (694, 0.10059909096557137),
 (695, 0.03919309008348103),
 (696, 0.049341371149144844),
 (697, 0.08351476906593233),
 (698, 0.025149772741392844),
 (699, 0.0),
 (700, 0.033351867298253506),
 (701, 0.0),
 (702, 0.025923792368260635),
 (703, 0.024217973984824143),
 (704, 0.0),
 (705, 0.05542739954736933),
 (706, 0.024217973984824143),
 (707, 0.07332355751067667),
 (708, 0.0),
 (709, 0.04599220498182739),
 (710, 0.02194227995205747),
 (711, 0.03126526997403613),
 (712, 0.02707651805369412),
 (713, 0.0),
 (714, 0.0),
 (715, 0.0),
 (716, 0.06350006350009525),
 (717, 0.09962709627734359),
 (718, 0.0),
 (719, 0.049813548138671795),
 (720, 0.0),
 (721, 0.0),
 (722, 0.07777137710478191),
 (723, 0.0),
 (724, 0.05477910356647767),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.027713699773684666),
 (729, 0.0),
 (730, 0.06818952339930237),
 (731, 0.030358837035945812),
 (732, 0.0),
 (733, 0.07014785603174337),
 (734, 0.025923792368260635),
 (735, 0.0),
 (736, 0.06788442333021306),
 (737, 0.029526929767874632),
 (738, 0.08032193289024989),
 (739, 0.0),
 (740, 0.024670685574572422),
 (741, 0.0),
 (742, 0.037450294313656915),
 (743, 0.0),
 (744, 0.0),
 (745, 0.03456505649101418),
 (746, 0.024441185836892216),
 (747, 0.04490132550669373),
 (748, 0.0),
 (749, 0.022450662753346864),
 (750, 0.023789303403490326),
 (751, 0.0),
 (752, 0.025149772741392844),
 (753, 0.0),
 (754, 0.029526929767874632),
 (755, 0.08648775001288211),
 (756, 0.0),
 (757, 0.0),
 (758, 0.1070959105203332),
 (759, 0.026481357066618805),
 (760, 0.030358837035945812),
 (761, 0.033351867298253506),
 (762, 0.03522349768381735),
 (763, 0.0),
 (764, 0.06350006350009525),
 (765, 0.02875986542715254),
 (766, 0.02913582733740325),
 (767, 0.0),
 (768, 0.0),
 (769, 0.03666177875533833),
 (770, 0.07620007620011429),
 (771, 0.0),
 (772, 0.03666177875533833),
 (773, 0.04490132550669373),
 (774, 0.0),
 (775, 0.06670373459650701),
 (776, 0.049813548138671795),
 (777, 0.0),
 (778, 0.1338698881504165),
 (779, 0.0),
 (780, 0.04490132550669373),
 (781, 0.03829197905337418),
 (782, 0.05415303610738824),
 (783, 0.037450294313656915),
 (784, 0.05542739954736933),
 (785, 0.04388455990411494),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0535479552601666),
 (789, 0.0),
 (790, 0.0),
 (791, 0.0),
 (792, 0.08740748201220976),
 (793, 0.0885807893036239),
 (794, 0.03456505649101418),
 (795, 0.0),
 (796, 0.03919309008348103),
 (797, 0.0),
 (798, 0.0),
 (799, 0.0),
 (800, 0.0),
 (801, 0.0),
 (802, 0.030358837035945812),
 (803, 0.05296271413323761),
 (804, 0.029934217004462485),
 (805, 0.03126526997403613),
 (806, 0.0),
 (807, 0.0),
 (808, 0.0),
 (809, 0.06582683985617241),
 (810, 0.03522349768381735),
 (811, 0.0),
 (812, 0.09776474334756886),
 (813, 0.0267739776300833),
 (814, 0.0),
 (815, 0.022809896167307987),
 (816, 0.0),
 (817, 0.0),
 (818, 0.1402481783633036),
 (819, 0.025149772741392844),
 (820, 0.03556714970147894),
 (821, 0.10722837304532315),
 (822, 0.023789303403490326),
 (823, 0.027389551783238836),
 (824, 0.0),
 (825, 0.0),
 (826, 0.03666177875533833),
 (827, 0.07544931822417852),
 (828, 0.0),
 (829, 0.0),
 (830, 0.06253053994807226),
 (831, 0.0),
 (832, 0.0),
 (833, 0.0),
 (834, 0.0),
 (835, 0.08627959628145762),
 (836, 0.0),
 (837, 0.0),
 (838, 0.021780342093451605),
 (839, 0.04233337566673017),
 (840, 0.0),
 (841, 0.05239625170622461),
 (842, 0.04525628222014204),
 (843, 0.060717674071891624),
 (844, 0.030358837035945812),
 (845, 0.04324387500644106),
 (846, 0.0),
 (847, 0.0),
 (848, 0.16816968473377),
 (849, 0.059053859535749265),
 (850, 0.048001536073731935),
 (851, 0.02913582733740325),
 (852, 0.0),
 (853, 0.03394221166510653),
 (854, 0.030358837035945812),
 (855, 0.029526929767874632),
 (856, 0.0),
 (857, 0.0),
 (858, 0.04490132550669373),
 (859, 0.033351867298253506),
 (860, 0.05810201339876483),
 (861, 0.022809896167307987),
 (862, 0.029934217004462485),
 (863, 0.0),
 (864, 0.02194227995205747),
 (865, 0.0),
 (866, 0.049813548138671795),
 (867, 0.0),
 (868, 0.04716666306365782),
 (869, 0.056796183424706485),
 (870, 0.027713699773684666),
 (871, 0.027713699773684666),
 (872, 0.0),
 (873, 0.0),
 (874, 0.029934217004462485),
 (875, 0.0),
 (876, 0.0),
 (877, 0.03592106040535498),
 (878, 0.03829197905337418),
 (879, 0.0),
 (880, 0.0),
 (881, 0.03829197905337418),
 (882, 0.03080205518168487),
 (883, 0.0),
 (884, 0.029526929767874632),
 (885, 0.0),
 (886, 0.026198125853112306),
 (887, 0.019480930197663147),
 (888, 0.0),
 (889, 0.0),
 (890, 0.029934217004462485),
 (891, 0.05415303610738824),
 (892, 0.09600307214746387),
 (893, 0.05648325441285857),
 (894, 0.032791291789197645),
 (895, 0.06160411036336974),
 (896, 0.0),
 (897, 0.0),
 (898, 0.0),
 (899, 0.0),
 (900, 0.027389551783238836),
 (901, 0.030358837035945812),
 (902, 0.026481357066618805),
 (903, 0.03592106040535498),
 (904, 0.023186944788008413),
 (905, 0.0),
 (906, 0.04356068418690321),
 (907, 0.0),
 (908, 0.0),

In [100]:
sorted(list(enumerate(similarity[1])),reverse=True, key=lambda x:x[1])[1:6]

[(12, 0.3522349768381735),
 (199, 0.2220361701711518),
 (3572, 0.1914598952668709),
 (17, 0.18396881992730957),
 (848, 0.16816968473377)]

In [97]:
sorted(similarity[1], reverse=True)

[1.0000000000000002,
 0.3522349768381735,
 0.2220361701711518,
 0.1914598952668709,
 0.18396881992730957,
 0.16816968473377,
 0.16433731069943303,
 0.1531679162134967,
 0.15089863644835705,
 0.1496710850223124,
 0.1402481783633036,
 0.13912166872805048,
 0.13856849886842332,
 0.1338698881504165,
 0.1338698881504165,
 0.1338698881504165,
 0.1338698881504165,
 0.13068205256070964,
 0.12961896184130317,
 0.1270001270001905,
 0.1270001270001905,
 0.12443420336765101,
 0.12361284651454937,
 0.12361284651454937,
 0.12220592918446108,
 0.12143534814378325,
 0.12097769771854963,
 0.12048289933537483,
 0.11973686801784994,
 0.11973686801784994,
 0.11973686801784994,
 0.11810771907149853,
 0.11757927025044308,
 0.11620402679752964,
 0.11498051245456849,
 0.11487593716012254,
 0.11487593716012252,
 0.11359236684941297,
 0.11235088294097074,
 0.11235088294097074,
 0.11235088294097074,
 0.11235088294097074,
 0.11219854269064289,
 0.11219854269064289,
 0.11085479909473867,
 0.11085479909473867,
 0.11085479909473865,
 0.109985336266015,
 0.10971139976028735,
 0.10830607221477648,
 0.10830607221477648,
 0.10776318121606496,
 0.10722837304532315,
 0.10722837304532315,
 0.1070959105203332,
 0.1061822175603132,
 0.10592542826647522,
 0.10592542826647522,
 0.10592542826647522,
 0.10592542826647522,
 0.10592542826647522,
 0.10567049305145204,
 0.10479250341244922,
 0.10479250341244922,
 0.10417859945721022,
 0.10369516947304254,
 0.10369516947304254,
 0.10369516947304254,
 0.10369516947304254,
 0.10369516947304254,
 0.10369516947304253,
 0.10369516947304253,
 0.10369516947304253,
 0.10369516947304253,
 0.10263160115815709,
 0.1018266349953196,
 0.1016001016001524,
 0.1016001016001524,
 0.1016001016001524,
 0.10059909096557137,
 0.10059909096557137,
 0.10059909096557137,
 0.10059909096557137,
 0.09962709627734359,
 0.09962709627734359,
 0.09962709627734359,
 0.09962709627734359,
 0.09962709627734359,
 0.09868274229828969,
 0.09857121533596891,
 0.09837387536759294,
 0.09837387536759293,
 0.09837387536759293,
 0.09776474334756886,
 0.09776474334756886,
 0.09776474334756886,
 0.09677419354838712,
 0.09677419354838712,
 0.09677419354838712,
 0.09677419354838712,
 0.09600307214746387,
 0.09600307214746387,
 0.09600307214746387,
 0.09600307214746387,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.09525009525014289,
 0.0951572136139613,
 0.09433332612731564,
 0.09379580992210838,
 0.09379580992210838,
 0.09379580992210838,
 0.09353047470899115,
 0.09344252878008429,
 0.09312101115961707,
 0.09274777915203365,
 0.09274777915203365,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09165444688834581,
 0.09123958466923195,
 0.09107651110783743,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.0891091838708226,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.08843153765707637,
 0.08776911980822988,
 0.08740748201220976,
 0.08740748201220976,
 0.08712136837380642,
 0.08712136837380642,
 0.08712136837380642,
 0.08712136837380642,
 0.08648775001288211,
 0.08648775001288211,
 0.08648775001288211,
 0.08627959628145762,
 0.08627959628145762,
 0.08526091126389751,
 0.08526091126389751,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08466675133346034,
 0.08466675133346034,
 0.08466675133346034,
 0.08466675133346034,
 0.08466675133346034,
 0.08466675133346034,
 0.08466675133346034,
 0.08466675133346034,
 0.08466675133346034,
 0.08414890701798217,
 0.08414890701798217,
 0.08414890701798217,
 0.08414890701798217,
 0.08414890701798217,
 0.08414890701798217,
 0.084084842366885,
 0.0837414038627107,
 0.08351476906593233,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.08295613557843401,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08216865534971651,
 0.08216865534971651,
 0.08216865534971651,
 0.08216865534971651,
 0.08216865534971651,
 0.08216865534971651,
 0.08216865534971651,
 0.08216865534971651,
 0.0813451834782084,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08082870090099549,
 0.0803219328902499,
 0.0803219328902499,
 0.0803219328902499,
 0.0803219328902499,
 0.0803219328902499,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.07944407119985641,
 0.07944407119985641,
 0.07944407119985641,
 0.07933635037580192,
 0.07859437755933692,
 0.07838618016696206,
 0.07838618016696206,
 0.07838618016696206,
 0.07838618016696206,
 0.07838618016696206,
 0.07838618016696206,
 0.07777137710478191,
 0.07777137710478191,
 0.07777137710478191,
 0.07777137710478191,
 0.07777137710478191,
 0.07777137710478191,
 0.07697370086861782,
 0.07697370086861782,
 0.07697370086861782,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07620007620011429,
 0.07620007620011429,
 0.07620007620011429,
 0.07544931822417852,
 0.07544931822417852,
 0.07544931822417852,
 0.07544931822417852,
 0.07544931822417852,
 0.07544931822417852,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.07490058862731383,
 0.0748355425111562,
 0.0747203222080077,
 0.0747203222080077,
 0.07401205672371727,
 0.07401205672371727,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067667,
 0.07332355751067665,
 0.07332355751067665,
 0.07332355751067665,
 0.07332355751067665,
 0.07265392195447243,
 0.07265392195447243,
 0.07265392195447243,
 0.07265392195447243,
 0.07265392195447243,
 0.07200230411059791,
 0.07200230411059791,
 0.07200230411059791,
 0.07184212081070997,
 0.07184212081070997,
 0.07184212081070997,
 0.07184212081070997,
 0.07184212081070997,
 0.07184212081070997,
 0.07148558203021543,
 0.07121813478786003,
 0.07074999459548673,
 0.07074999459548673,
 0.07074999459548673,
 0.07074999459548673,
 0.07074999459548673,
 0.07074999459548673,
 0.0704469953676347,
 0.0704469953676347,
 0.0704469953676347,
 0.0704469953676347,
 0.0704469953676347,
 0.0704469953676347,
 0.0704469953676347,
 0.07014785603174337,
 0.07014785603174337,
 0.07014785603174337,
 0.07014785603174337,
 0.07014785603174337,
 0.07014785603174335,
 0.06956083436402524,
 0.06913011298202835,
 0.06913011298202835,
 0.06913011298202835,
 0.06913011298202835,
 0.06913011298202835,
 0.06913011298202835,
 0.0689883074727411,
 0.0689883074727411,
 0.0689883074727411,
 0.06849877452507418,
 0.06842968850192396,
 0.06842968850192396,
 0.06842968850192396,
 0.06842968850192396,
 0.06818952339930237,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021306,
 0.06788442333021305,
 0.06788442333021305,
 0.06788442333021305,
 0.06788442333021305,
 0.06735198826004059,
 0.0672863110252489,
 0.06683188790311695,
 0.06683188790311695,
 0.06683188790311695,
 0.06683188790311695,
 0.06683188790311695,
 0.06683188790311695,
 0.06683188790311695,
 0.06670373459650701,
 0.06670373459650701,
 0.06670373459650701,
 0.06670373459650701,
 0.06670373459650701,
 0.06670373459650701,
 0.06670373459650701,
 0.06670373459650701,
 0.06670373459650701,
 0.06632365324280728,
 0.06632365324280728,
 0.06582683985617241,
 0.06582683985617241,
 0.06558258357839529,
 0.06558258357839529,
 0.06558258357839529,
 0.06558258357839529,
 0.06558258357839529,
 0.06558258357839529,
 0.06558258357839529,
 0.06558258357839529,
 0.06558258357839529,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06486581250966159,
 0.06486581250966159,
 0.06451612903225808,
 0.06451612903225808,
 0.06451612903225808,
 0.06451612903225808,
 0.06451612903225808,
 0.06451612903225808,
 0.06451612903225808,
 0.06451612903225808,
 0.06440081861116377,
 0.06394568344792313,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06350006350009525,
 0.06306363177516375,
 0.06263607679944926,
 0.06263607679944924,
 0.06263607679944924,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06221710168382551,
 0.06221710168382551,
 0.06221710168382551,
 0.06180642325727469,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06160411036336974,
 0.06140377126253594,
 0.06137886606124273,
 0.06115607452367586,
 0.061008887608656304,
 0.061008887608656304,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.060717674071891624,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05986843400892497,
 0.05950226278185144,
 0.059254382556024304,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.059053859535749265,
 0.05878963512522154,
 0.058442790592989444,
 0.058442790592989444,
 0.058442790592989444,
 0.0582716546748065,
 0.0582716546748065,
 0.0582716546748065,
 0.0582716546748065,
 0.0582716546748065,
 0.0582716546748065,
 0.05810201339876483,
 0.05810201339876483,
 0.05789203073355576,
 0.05776712868787001,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05751973085430508,
 0.05743796858006127,
 0.05743796858006127,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.05679618342470648,
 0.05679618342470648,
 0.05648325441285857,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.056099271345321444,
 0.05587260669577024,
 0.05557461733534294,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05542739954736933,
 0.05477910356647767,
 0.05477910356647767,
 0.05477910356647767,
 0.05477910356647767,
 0.05477910356647767,
 0.05477910356647767,
 0.05477910356647767,
 0.05477910356647767,
 0.05477910356647767,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05415303610738824,
 0.05388159060803248,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.0535479552601666,
 0.05296271413323761,
 0.05296271413323761,
 0.05296271413323761,
 0.05296271413323761,
 0.05296271413323761,
 0.05296271413323761,
 0.05296271413323761,
 0.05296271413323761,
 0.05296271413323761,
 0.05239625170622461,
 0.05239625170622461,
 0.05239625170622461,
 0.05239625170622461,
 0.05239625170622461,
 0.05239625170622461,
 0.05239625170622461,
 0.05239625170622461,
 0.05239625170622461,
 0.05233442719890389,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.05184758473652127,
 0.051315800579078544,
 0.051315800579078544,
 0.051315800579078544,
 0.051315800579078544,
 0.051315800579078544,
 0.051315800579078544,
 0.051315800579078544,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.0508000508000762,
 0.050464733268936676,
 0.05029954548278569,
 0.05029954548278569,
 0.05029954548278569,
 0.05029954548278569,
 0.05029954548278569,
 0.05029954548278569,
 0.05029954548278569,
 0.05029954548278569,
 0.05029954548278569,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.049813548138671795,
 0.04960202468574339,
 0.04960202468574339,
 0.04939317312787276,
 0.04939317312787276,
 0.049341371149144844,
 0.049341371149144844,
 0.049341371149144844,
 0.049341371149144844,
 0.049341371149144844,
 0.049341371149144844,
 0.049341371149144844,
 0.049341371149144844,
 0.04888237167378443,
 0.04888237167378443,
 0.04888237167378443,
 0.04888237167378443,
 0.04888237167378443,
 0.04888237167378443,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048435947969648285,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.048001536073731935,
 0.04781218016373176,
 0.04762504762507144,
 0.04757860680698065,
 0.04757860680698065,
 0.04757860680698065,
 0.04757860680698065,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04716666306365782,
 0.04676523735449557,
 0.04676523735449557,
 0.04676523735449557,
 0.04676523735449557,
 0.04676523735449557,
 0.04676523735449557,
 0.04676523735449557,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046373889576016826,
 0.046034149545932046,
 0.04599220498182739,
 0.04599220498182739,
 0.04599220498182739,
 0.04599220498182739,
 0.04599220498182739,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.04561979233461597,
 0.045538255553918716,
 0.04525628222014204,
 0.04525628222014204,
 0.04525628222014204,
 0.04525628222014204,
 0.04525628222014204,
 0.04525628222014204,
 0.04525628222014204,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.04490132550669373,
 0.0445545919354113,
 0.0445545919354113,
 0.0445545919354113,
 0.0445545919354113,
 0.0445545919354113,
 0.044215768828538185,
 0.04388455990411494,
 0.04388455990411494,
 0.04388455990411494,
 0.04388455990411494,
 0.04388455990411494,
 0.04388455990411494,
 0.04388455990411494,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,
 0.04356068418690321,

In [109]:
def recommend(movie):
    movie_index = new_df[new_df['title']== movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [111]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
Batman v Superman: Dawn of Justice
Synecdoche, New York

In [112]:
import pickle

In [113]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [114]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [116]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [117]:
pickle.dump(similarity,open('similarity.pkl','wb'))